
project_id = "ypsufujqhpixachonnnh"

[functions.create-payment]
verify_jwt = false

[functions.handle-payment-success]
verify_jwt = false

[functions.send-delivery-email]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-validate-session]
verify_jwt = false

[functions.get-product-download]
verify_jwt = false
