// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypsufujqhpixachonnnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwc3VmdWpxaHBpeGFjaG9ubm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDg5OTIsImV4cCI6MjA2Mzg4NDk5Mn0.wmo4oTNrQLfCwnsiE9Z1aW6JLNc-4uQghhSQC0IcRu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);